[package]
name = "rs-scout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
sbert = "0.3.0"
serde = { version = "1.0.163", features = ["derive"] }
